#!/bin/sh

# Config by
  # ____                            _    _         _             _    _
 # / ___|_ __ ___  _ __  _   _     / \  | | ____ _| |_ ___ _   _| | _(_)
# | |   | '__/ _ \| '_ \| | | |   / _ \ | |/ / _` | __/ __| | | | |/ / |
# | |___| | | (_) | | | | |_| |  / ___ \|   < (_| | |_\__ \ |_| |   <| |
 # \____|_|  \___/|_| |_|\__, | /_/   \_\_|\_\__,_|\__|___/\__,_|_|\_\_|
                       # |___/

# Program alias
alias ssd-check="sudo smartctl -a /dev/nvme0n1 | grep -E -- 'Data Units Read:|Data Units Written:|Percentage Used:'"
alias grep='grep --color=auto'
alias vi='nvim'
alias ls='/usr/bin/ls -Alh --color=always --group-directories-first' # my preferred listing
alias la='/usr/bin/ls -ah --color=always --group-directories-first'  # all files and dirs
alias df='df -h -x devtmpfs -x tmpfs -x usbfs -x loop'                          # human-readable sizes
alias free='free -m -h'                      # show sizes in MB
alias spotdl='spotdl --output-format ogg -p "{artist}/{album}/{artists} - {title}.{ext}" --dt 8 --st 8'
alias pacman-rm-orphans='sudo pacman -Rnsc $(pacman -Qtdq)'
alias update-grub='sudo grub-mkconfig -o /boot/grub/grub.cfg'

# Function aliases
alias yta='yt-dlp -x -f bestaudio --external-downloader aria2c --external-downloader-args "-j 16 -s 16 -x 16 -k 5M" --audio-format vorbis -o "%(title)s.%(ext)s"'
alias ytvb='yt-dlp --merge-output-format mp4 -f "bestvideo+bestaudio[ext=m4a]/best" --embed-thumbnail --external-downloader aria2c --external-downloader-args "-j 16 -s 16 -x 16 -k 5M" --add-metadata -o "%(title)s.%(ext)s"'
alias ytvf='yt-dlp --merge-output-format mp4 --format best --embed-thumbnail --external-downloader aria2c --external-downloader-args "-j 16 -s 16 -x 16 -k 5M" --add-metadata -o "%(title)s.%(ext)s"'

alias dl='aria2c -j 16 -s 16 -x 16 -k 5M --file-allocation=none'
alias lf='lf-run $@'
alias exif-clean="exiftool -overwrite_original -recurse -all="

# functions
fcd () {
    cd "$(find -type d | fzf)"
}

fopen () {
    xdg-open "$(find -type f | fzf)"
}

fga () {
    git add $(git status -s | awk '{ print $2 }' | fzf -m)
}

vish () {
    nvim $(which $1)
}

alias h="history 1 -1 | cut -c 8- | sort | uniq | fzf | tr -d '\n' | xclip -sel c"
