#!/bin/sh

# Program alias
alias ssd-check="sudo smartctl -a /dev/nvme0n1 | grep -E -- 'Data Units Read:|Data Units Written:|Percentage Used:'"
alias grep='grep --color=auto'
alias vi='nvim'
alias ls='/usr/bin/ls -Alh --color=always --group-directories-first' # my preferred listing
alias la='/usr/bin/ls -ah --color=always --group-directories-first'  # all files and dirs
alias df='df -h -x devtmpfs -x tmpfs -x usbfs -x loop'                          # human-readable sizes
alias free='free -m -h'                      # show sizes in MB
alias spotdl='spotdl --output-format ogg -p "{artist}/{album}/{artists} - {title}.{ext}" --dt 8 --st 8'
alias pacman-rm-orphans='sudo pacman -Rnsc $(pacman -Qtdq)'
alias update-grub='sudo grub-mkconfig -o /boot/grub/grub.cfg'
alias dust='du -hd1 | sort -hr | sed "s/.\///g"'

# Function aliases
alias yta='yt-dlp -x -f bestaudio --external-downloader aria2c --external-downloader-args "-j 16 -s 16 -x 16 -k 5M" --audio-format vorbis -o "%(title)s.%(ext)s"'
alias ytvb='yt-dlp --merge-output-format mp4 -f "bestvideo+bestaudio[ext=m4a]/best" --embed-thumbnail --external-downloader aria2c --external-downloader-args "-j 16 -s 16 -x 16 -k 5M" --add-metadata -o "%(title)s.%(ext)s"'
alias ytvf='yt-dlp --merge-output-format mp4 --format best --embed-thumbnail --external-downloader aria2c --external-downloader-args "-j 16 -s 16 -x 16 -k 5M" --add-metadata -o "%(title)s.%(ext)s"'

alias dl='aria2c -j 16 -s 16 -x 16 -k 5M --file-allocation=none'
alias lf='lf-run $@'

# functions

# Cd into a directory using fzf
fcd () {
    cd "$(find -type d | fzf)"
}

# Quicly choose stuff to add using fzf
fga () {
    git add $(git status -s | awk '{ print $2 }' | fzf -m)
}

# Open a script in path with vim quicly
vish () {
    nvim $(which $1)
}

# Open a directory indide .config with vim
vicfg () {
    dir=$(pwd)
    cd ~/.config
    [[ "$1" != "" ]] && nvim $1
    cd $dir
}

# Change into a directory in .config
cfg () {
    dir=$(pwd)
    cd ~/.config
    [[ "$1" != "" ]] && cd $1 || cd $dir
}

# Create a directory and change into it
md () {
    mkdir -p "$@" && cd "$@"
}

# Move a file and create a link in it's place
mvln () {
    from=$(readlink -f $1)
    to=$(readlink -f $2)
    mv $from $to
    ln -s $to $from
}
