#!/bin/sh

# Autostart
riverctl spawn 'dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP'
riverctl spawn 'systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP'
riverctl spawn 'wbg ~/pics/wallpaper.jpg'
riverctl spawn 'mouse_detect.sh'
riverctl spawn waybar
riverctl spawn transmission-daemon
riverctl spawn syncthing
riverctl spawn dunst
riverctl spawn keepassxc
riverctl spawn "mpd --no-daemon"
riverctl spawn mpDris2

# Programs keybindings
riverctl map normal Super Return spawn $TERMINAL

riverctl map normal Super D spawn 'bemenu-run -p "Run: "'
riverctl map normal Super F12 spawn dmenu-ryzenadj

riverctl map normal Super+Shift E spawn dmenu-power-menu

riverctl map normal Super B spawn firefox
riverctl map normal Super+Shift B spawn 'firefox -P unsecure'
riverctl map normal Super N spawn "$TERMINAL -e newsboat"

riverctl map normal Super+Shift F12 spawn gaming-time

# riverctl map normal None Print dmenu-screenshot

# Keychaining some dmenu  scripts
riverctl declare-mode dmenu
riverctl map normal Super P enter-mode dmenu
riverctl map dmenu None Escape enter-mode normal
riverctl map dmenu None G spawn "dmenu-games & riverctl enter-mode normal"
riverctl map dmenu None E spawn "dmenu-configs & riverctl enter-mode normal"
riverctl map dmenu None T spawn "dmenu-transmission & riverctl enter-mode normal"
riverctl map dmenu None U spawn "dmenu-usb-man & riverctl enter-mode normal"
riverctl map dmenu None W spawn "dmenu-wifi & riverctl enter-mode normal"
riverctl map dmenu None D spawn "dmenu-runner & riverctl enter-mode normal"
riverctl map dmenu None K spawn "dmenu-kill & riverctl enter-mode normal"

riverctl declare-mode gui
riverctl map normal Super G enter-mode gui
riverctl map gui None Escape enter-mode normal
riverctl map gui None L spawn "waylock & riverctl enter-mode normal"


# River Keybindings
riverctl map normal Super+Shift Q close

riverctl map normal Super+Control E exit

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# Super+Return to bump the focused view to the top of the layout stack
riverctl map normal Super+Shift Return zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

# Super+Alt+Shif+{H,J,K,L} to resize views
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Focus last used tag
riverctl map normal Super Tab focus-previous-tags

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+Space to toggle float
riverctl map normal Super+Shift Space toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super F11 toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal Super+Shift F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super+Shift F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'sb-volume-update up'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'sb-volume-update down'
    riverctl map $mode None XF86AudioMute         spawn 'sb-volume-update mute'
    riverctl map $mode None XF86AudioPlay  spawn 'dmenu-playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'dmenu-playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'dmenu-playerctl next'

    riverctl map $mode None XF86MonBrightnessUp   spawn 'sb-backlight-update up'
    riverctl map $mode None XF86MonBrightnessDown spawn 'sb-backlight-update down'
done

# Set background and border color
riverctl background-color 0x002b36
riverctl border-color-focused 0x939ab7
riverctl border-color-unfocused 0x5b6078
riverctl border-width 3

# Set keyboard repeat rate
riverctl set-repeat 50 300
riverctl hide-cursor timeout 5000

# Make certain views start floating
riverctl float-filter-add app-id float
riverctl float-filter-add title "Password Required - Mozilla Thunderbird"

# Set app-ids and titles of views which should use client side decorations
riverctl csd-filter-add app-id "gedit"

# Spawn new window left in the stack
riverctl attach-mode bottom

# Mouse configuration
riverctl input "pointer-1578-16734-MOSART_Semi._2.4G_INPUT_DEVICE_Mouse" accel-profile flat
riverctl input "pointer-1578-16734-MOSART_Semi._2.4G_INPUT_DEVICE_Mouse" pointer-accel 0.0

# Touchpad configuration
riverctl input "pointer-1267-12610-ELAN0515:01_04F3:3142_Touchpad" click-method clickfinger
riverctl input "pointer-1267-12610-ELAN0515:01_04F3:3142_Touchpad" drag enabled
riverctl input "pointer-1267-12610-ELAN0515:01_04F3:3142_Touchpad" drag-lock enabled
riverctl input "pointer-1267-12610-ELAN0515:01_04F3:3142_Touchpad" disable-while-typing enabled
riverctl input "pointer-1267-12610-ELAN0515:01_04F3:3142_Touchpad" middle-emulation enabled
riverctl input "pointer-1267-12610-ELAN0515:01_04F3:3142_Touchpad" natural-scroll enabled
riverctl input "pointer-1267-12610-ELAN0515:01_04F3:3142_Touchpad" tap enabled
riverctl input "pointer-1267-12610-ELAN0515:01_04F3:3142_Touchpad" tap-button-map left-right-middle
riverctl input "pointer-1267-12610-ELAN0515:01_04F3:3142_Touchpad" scroll-method edge


# Set and exec into the default layout generator, rivertile.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
exec rivertile -view-padding 4 -outer-padding 4 -main-ratio 0.5
