#!/bin/sh
sudo ryzenset set normal-mode

userresources="$XDG_CONFIG_HOME/X11/xresources"
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
if [ -f $sysresources ]; then

    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then

    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# setup xserver
# mode=$(envycontrol -q | awk '{ print $5 }')
# if [ "$mode" = "nvidia" ]; then
#     xrandr --setprovideroutputsource "AMD Radeon Vega 8 Graphics @ pci:0000:05:00.0" NVIDIA-0
#     xrandr --auto
# fi


[ -f "$HOME/.cache/bspwm.lock" ] && rm $HOME/.cache/bspwm.lock
[ -f "$HOME/.cache/dwm.lock" ] && rm $HOME/.cache/dwm.lock
[ -f "$HOME/.cache/gaming.lock" ] && rm $HOME/.cache/gaming.lock

optimus-fix.sh
mouse_detect.sh x11
xsetroot -cursor_name left_ptr
# xwallpaper --stretch $HOME/pics/KurzegartDNA.png

exec qtile start
