#!/usr/bin/env sh

# power menu
alt + shift + e
  dmenu-power-menu

# Reload sxhkd
alt + control + r
  pkill -USR1 -x sxhkd

##---System Control---##

# Audio Control
{XF86AudioRaiseVolume,XF86AudioLowerVolume,XF86AudioMute}
  sb-volume-update { up, down, mute }

# Brightness
{XF86MonBrightnessUp,XF86MonBrightnessDown}
  sb-backlight-update { up, down }

# Player control keybindings
{XF86AudioPlay,XF86AudioPrev,XF86AudioNext}
  dmenu-playerctl {play-pause,previous,next}

##---Aplication Launchers---##

# terminal
alt + Return
	$TERMINAL

# Browser run
# alt + {_, shift + }b
alt + b
  librewolf
  # {$BROWSER, librewolf -P unsecure}

# Gui Programs
alt + g; l
  slock

# Terminal Programs with class
alt + t; {n,v,f,y}
  $TERMINAL --class {newsboat -e newsboat,\
    videos -e lf-run ~/vids, lf -e lf-run, ytfzf -e ytfzf}

##---Dmenu bindings---#

# Key chaining some certain scripts
alt + p; {g,e,t,u,w,d,k,l,b}
  {dmenu-games, dmenu-configs, dmenu-transmission, dmenu-usb-man,\
    dmenu-wifi, dmenu-runner, dmenu-kill,\
    dmenu-link-handler $(xclip -sel c -o), dmenu-browser}

# Regular binding some other one's
alt + {d,F12,c}
  {dmenu_run, dmenu-ryzenadj, clipmenu -l 10}

Print
  dmenu-screenshot

##---Gaming bindings---##
alt + shift + F12
  gaming-time

##---Buku bindings---##
ctrl + b; {a,o,e}
  {badd, dmenu-buku open, dmenu-buku edit}

##---Sripts---##
alt + F1
  sound-output-toggle
