#!/usr/bin/env sh
##---BSPWM Bindings---##

# System turn off
super + shift + e
    dmenu-power-menu

# Quit bsowm
super + ctrl + e
    bspc quit

# Close current window
super + shift + q
    bspc node -c

# Swap with biggest current window
super + shift + Return
    bspc node -s biggest.local

# Reload bspwm or polybar configuration
super + shift + {r,p}
    {bspc wm -r, pkill -USR1 polybar}

# Restart sxhkd
super + control + r
    pkill -usr1 -x sxhkd; quick-notify 'sxhkd' 'Reloaded config'

# Focus on window in direction
super + {h,j,k,l}
	bspc node -f {west ,south ,north ,east}

# Swap window with direction
super + shift + {h,j,k,l}
    bspc node -s {west,south,north,east}

# Focus on desktop
super + {1-9}
    bspc desktop -f {1-9}

# Send window to desktop
super + shift + {1-9}
    bspc node -d {1-9}

# Send window to desktop and swap to desktop
super + control + {1-9}
    bspc node -d {1-9} --follow

# Focus the next/previous node in the current desktop
super + {_, shift + }m
        bspc node -f {next, prev}.local.!hidden.window

# Toggle floating on and off
super + shift + space
    bspc node focused.tiled -t floating || bspc node focused.floating -t tiled

# Last used workspace/window
{super,alt} + Tab
    bspc {desktop,node} -f last

# Fullscreen toggle
super + F11
    bspc node -t \~fullscreen

##---System Control---##

# Audio Control
{XF86AudioRaiseVolume,XF86AudioLowerVolume,XF86AudioMute}
    sb-volume-update { up, down, mute }

# Brightness
{XF86MonBrightnessUp,XF86MonBrightnessDown}
    sb-backlight-update { up, down }

# Player control keybindings
{XF86AudioPlay,XF86AudioPrev,XF86AudioNext}
    dmenu-playerctl {play-pause,previous,next}

##---Application Launchers---##

# Gui Programs
super + Return
    $TERMINAL

# Browser run
super + {_, shift + }b
    {$BROWSER, firefox -P unsecure}

# Gui Programs
super + g; l
    slock

# Terminal Programs
super + n
    $TERMINAL --class newsboat -e newsboat

##---Dmenu bindings---#

# Key chaining some certain scripts
super + p; {g,e,t,u,w,d,k}
    {dmenu-games, dmenu-configs, dmenu-transmission, dmenu-usb-man, dmenu-wifi, dmenu-runner, dmenu-kill}

# Regular binding some other one's
super + {d,F12,c}
    {dmenu_run, dmenu-ryzenadj, clipmenu -l 10}

Print
    dmenu-screenshot

##---Gaming bindings---##
super + {shift, ctrl} + F12
    {toggle-program picom --experimental-backends, gaming-time}

##---Scratchpads---##
super + F1
    scratchy spterm "kitty -o initial_window_width=1344 -o initial_window_height=864 -o remember_window_size=no --class spterm"

super + F2
    scratchy splf "kitty -o initial_window_width=1344 -o initial_window_height=864 -o remember_window_size=no --class splf -e lf-run"
