#!/usr/bin/env sh

# quit dk
alt + control + e
    dkcmd exit

# reload dk
alt + shift + r
    dkcmd reload

# close window, swap tiled window in/out of master
alt + shift + {q,Return}
	dkcmd win {kill,swap}

# focus next or previous window
alt + {j,k}
	dkcmd win focus {next,prev}

# move the active window up/down the stack
alt + shift + {j,k}
	dkcmd win mvstack {down,upMS}

# change master and stack ratio
alt + {h,l}
	dkcmd set msplit {-,+}0.025

# view, send, or follow to a workspace (by number)
alt + {_,shift + ,ctrl + }{1-9}
	dkcmd ws {view,send,follow} {1-9}

# focues last used workspace cycle tiled windows in place
{alt, alt} + Tab
    dkcmd {ws view last, win cycle}

# toggle fullscreen
alt + F11
	dkcmd win full

# toggle floating or sticky
alt + shift + space
	dkcmd win float

# change number of windows in master or first stack
alt + {comma, period}
	dkcmd set master {+1,-1}
