theme = "catppuccin_mocha"

# General helix setting
[editor]
line-number = 'relative'
cursorline = true
color-modes = true

# Cursor
[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

# Statusline
[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name", "diagnostics"]
right = ["selections", "position"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

# File picker
[editor.file-picker]
hidden = false
parents = false

[editor.whitespace]
render = "none"

[editor.indent-guides]
render = false
character = "┊" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

# LSP Server configuration
[editor.lsp]
display-messages = true
auto-signature-help	= true
display-signature-help-docs	= true

# Auto-pairs
[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'
